version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    tty: true
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .docker/app
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      APP_NAME: 'CakePHP'
      APP_ENV: 'development'
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_DATABASE: 'cake_development'
      DB_DATABASE_TEST: 'cake_testing'
      DB_USERNAME: 'docker'
      DB_PASSWORD: 'docker'
      MAIL_DRIVER: 'smtp'
      MAIL_HOST: 'mail'
      MAIL_PORT: '1025'
      MAIL_USERNAME: 'null'
      MAIL_PASSWORD: 'null'
      MAIL_ENCRYPTION: 'null'
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    tty: true
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'docker'
      POSTGRES_ROOT_PASSWORD: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'cake_development'
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
